type Image = {
  image_url: string;
  small_image_url?: string;
};

type Images = {
  jpg: Image;
  webp: Image;
};

/**
 * Generated by https://quicktype.io
 * https://docs.api.jikan.moe/#tag/characters/operation/getCharacterById
 */
export type Character = {
  mal_id: number;
  url: string;
  images: Images;
  name: string;
  name_kanji: string | null;
  nicknames: string[];
  favorites: number | null;
  about: string | null;
};
